name: CD workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /flask-app
            git pull

            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -aq)

            docker pull my-docker-image
            docker run -dp 8000:8000 my-docker-image
